resources:
  repositories:
  - repository: self
    type: git
    ref: main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: DownloadSecureFile@1
    name: databricks
    displayName: Download secure file
    inputs:
      secureFile: 993ff0d8-4033-463b-be6a-3ba44e309c80
  - task: CmdLine@2
    displayName: Install CLI
    inputs:
      script: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
  - task: CmdLine@2
    displayName: validade dev
    inputs:
      script: databricks bundle validate
  - task: CmdLine@2
    displayName: deploy to dev
    inputs:
      script: databricks bundle deploy
  - task: CmdLine@2
    displayName: run job on dev
    inputs:
      script: databricks bundle run serverless_task
...
